 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/degrees", type: :request do
  # Degree. As you add validations to Degree, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Degree.create! valid_attributes
      get degrees_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      degree = Degree.create! valid_attributes
      get degree_url(degree)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_degree_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      degree = Degree.create! valid_attributes
      get edit_degree_url(degree)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Degree" do
        expect {
          post degrees_url, params: { degree: valid_attributes }
        }.to change(Degree, :count).by(1)
      end

      it "redirects to the created degree" do
        post degrees_url, params: { degree: valid_attributes }
        expect(response).to redirect_to(degree_url(Degree.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Degree" do
        expect {
          post degrees_url, params: { degree: invalid_attributes }
        }.to change(Degree, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post degrees_url, params: { degree: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested degree" do
        degree = Degree.create! valid_attributes
        patch degree_url(degree), params: { degree: new_attributes }
        degree.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the degree" do
        degree = Degree.create! valid_attributes
        patch degree_url(degree), params: { degree: new_attributes }
        degree.reload
        expect(response).to redirect_to(degree_url(degree))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        degree = Degree.create! valid_attributes
        patch degree_url(degree), params: { degree: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested degree" do
      degree = Degree.create! valid_attributes
      expect {
        delete degree_url(degree)
      }.to change(Degree, :count).by(-1)
    end

    it "redirects to the degrees list" do
      degree = Degree.create! valid_attributes
      delete degree_url(degree)
      expect(response).to redirect_to(degrees_url)
    end
  end
end
