 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/disciplines", type: :request do
  # Discipline. As you add validations to Discipline, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Discipline.create! valid_attributes
      get disciplines_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      discipline = Discipline.create! valid_attributes
      get discipline_url(discipline)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_discipline_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      discipline = Discipline.create! valid_attributes
      get edit_discipline_url(discipline)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Discipline" do
        expect {
          post disciplines_url, params: { discipline: valid_attributes }
        }.to change(Discipline, :count).by(1)
      end

      it "redirects to the created discipline" do
        post disciplines_url, params: { discipline: valid_attributes }
        expect(response).to redirect_to(discipline_url(Discipline.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Discipline" do
        expect {
          post disciplines_url, params: { discipline: invalid_attributes }
        }.to change(Discipline, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post disciplines_url, params: { discipline: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested discipline" do
        discipline = Discipline.create! valid_attributes
        patch discipline_url(discipline), params: { discipline: new_attributes }
        discipline.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the discipline" do
        discipline = Discipline.create! valid_attributes
        patch discipline_url(discipline), params: { discipline: new_attributes }
        discipline.reload
        expect(response).to redirect_to(discipline_url(discipline))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        discipline = Discipline.create! valid_attributes
        patch discipline_url(discipline), params: { discipline: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested discipline" do
      discipline = Discipline.create! valid_attributes
      expect {
        delete discipline_url(discipline)
      }.to change(Discipline, :count).by(-1)
    end

    it "redirects to the disciplines list" do
      discipline = Discipline.create! valid_attributes
      delete discipline_url(discipline)
      expect(response).to redirect_to(disciplines_url)
    end
  end
end
