 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/organization_types", type: :request do
  # OrganizationType. As you add validations to OrganizationType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      OrganizationType.create! valid_attributes
      get organization_types_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      organization_type = OrganizationType.create! valid_attributes
      get organization_type_url(organization_type)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_organization_type_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      organization_type = OrganizationType.create! valid_attributes
      get edit_organization_type_url(organization_type)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OrganizationType" do
        expect {
          post organization_types_url, params: { organization_type: valid_attributes }
        }.to change(OrganizationType, :count).by(1)
      end

      it "redirects to the created organization_type" do
        post organization_types_url, params: { organization_type: valid_attributes }
        expect(response).to redirect_to(organization_type_url(OrganizationType.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OrganizationType" do
        expect {
          post organization_types_url, params: { organization_type: invalid_attributes }
        }.to change(OrganizationType, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post organization_types_url, params: { organization_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested organization_type" do
        organization_type = OrganizationType.create! valid_attributes
        patch organization_type_url(organization_type), params: { organization_type: new_attributes }
        organization_type.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the organization_type" do
        organization_type = OrganizationType.create! valid_attributes
        patch organization_type_url(organization_type), params: { organization_type: new_attributes }
        organization_type.reload
        expect(response).to redirect_to(organization_type_url(organization_type))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        organization_type = OrganizationType.create! valid_attributes
        patch organization_type_url(organization_type), params: { organization_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested organization_type" do
      organization_type = OrganizationType.create! valid_attributes
      expect {
        delete organization_type_url(organization_type)
      }.to change(OrganizationType, :count).by(-1)
    end

    it "redirects to the organization_types list" do
      organization_type = OrganizationType.create! valid_attributes
      delete organization_type_url(organization_type)
      expect(response).to redirect_to(organization_types_url)
    end
  end
end
