 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/portfolio_image_call_outs", type: :request do
  # PortfolioImageCallOut. As you add validations to PortfolioImageCallOut, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PortfolioImageCallOut.create! valid_attributes
      get portfolio_image_call_outs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      portfolio_image_call_out = PortfolioImageCallOut.create! valid_attributes
      get portfolio_image_call_out_url(portfolio_image_call_out)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_portfolio_image_call_out_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      portfolio_image_call_out = PortfolioImageCallOut.create! valid_attributes
      get edit_portfolio_image_call_out_url(portfolio_image_call_out)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PortfolioImageCallOut" do
        expect {
          post portfolio_image_call_outs_url, params: { portfolio_image_call_out: valid_attributes }
        }.to change(PortfolioImageCallOut, :count).by(1)
      end

      it "redirects to the created portfolio_image_call_out" do
        post portfolio_image_call_outs_url, params: { portfolio_image_call_out: valid_attributes }
        expect(response).to redirect_to(portfolio_image_call_out_url(PortfolioImageCallOut.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PortfolioImageCallOut" do
        expect {
          post portfolio_image_call_outs_url, params: { portfolio_image_call_out: invalid_attributes }
        }.to change(PortfolioImageCallOut, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post portfolio_image_call_outs_url, params: { portfolio_image_call_out: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested portfolio_image_call_out" do
        portfolio_image_call_out = PortfolioImageCallOut.create! valid_attributes
        patch portfolio_image_call_out_url(portfolio_image_call_out), params: { portfolio_image_call_out: new_attributes }
        portfolio_image_call_out.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the portfolio_image_call_out" do
        portfolio_image_call_out = PortfolioImageCallOut.create! valid_attributes
        patch portfolio_image_call_out_url(portfolio_image_call_out), params: { portfolio_image_call_out: new_attributes }
        portfolio_image_call_out.reload
        expect(response).to redirect_to(portfolio_image_call_out_url(portfolio_image_call_out))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        portfolio_image_call_out = PortfolioImageCallOut.create! valid_attributes
        patch portfolio_image_call_out_url(portfolio_image_call_out), params: { portfolio_image_call_out: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested portfolio_image_call_out" do
      portfolio_image_call_out = PortfolioImageCallOut.create! valid_attributes
      expect {
        delete portfolio_image_call_out_url(portfolio_image_call_out)
      }.to change(PortfolioImageCallOut, :count).by(-1)
    end

    it "redirects to the portfolio_image_call_outs list" do
      portfolio_image_call_out = PortfolioImageCallOut.create! valid_attributes
      delete portfolio_image_call_out_url(portfolio_image_call_out)
      expect(response).to redirect_to(portfolio_image_call_outs_url)
    end
  end
end
