 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/portfolio_images", type: :request do
  # PortfolioImage. As you add validations to PortfolioImage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PortfolioImage.create! valid_attributes
      get portfolio_images_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      portfolio_image = PortfolioImage.create! valid_attributes
      get portfolio_image_url(portfolio_image)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_portfolio_image_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      portfolio_image = PortfolioImage.create! valid_attributes
      get edit_portfolio_image_url(portfolio_image)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PortfolioImage" do
        expect {
          post portfolio_images_url, params: { portfolio_image: valid_attributes }
        }.to change(PortfolioImage, :count).by(1)
      end

      it "redirects to the created portfolio_image" do
        post portfolio_images_url, params: { portfolio_image: valid_attributes }
        expect(response).to redirect_to(portfolio_image_url(PortfolioImage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PortfolioImage" do
        expect {
          post portfolio_images_url, params: { portfolio_image: invalid_attributes }
        }.to change(PortfolioImage, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post portfolio_images_url, params: { portfolio_image: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested portfolio_image" do
        portfolio_image = PortfolioImage.create! valid_attributes
        patch portfolio_image_url(portfolio_image), params: { portfolio_image: new_attributes }
        portfolio_image.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the portfolio_image" do
        portfolio_image = PortfolioImage.create! valid_attributes
        patch portfolio_image_url(portfolio_image), params: { portfolio_image: new_attributes }
        portfolio_image.reload
        expect(response).to redirect_to(portfolio_image_url(portfolio_image))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        portfolio_image = PortfolioImage.create! valid_attributes
        patch portfolio_image_url(portfolio_image), params: { portfolio_image: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested portfolio_image" do
      portfolio_image = PortfolioImage.create! valid_attributes
      expect {
        delete portfolio_image_url(portfolio_image)
      }.to change(PortfolioImage, :count).by(-1)
    end

    it "redirects to the portfolio_images list" do
      portfolio_image = PortfolioImage.create! valid_attributes
      delete portfolio_image_url(portfolio_image)
      expect(response).to redirect_to(portfolio_images_url)
    end
  end
end
