default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gabrielwalsh_development
  username: postgres
  password: amops

test:
  <<: *default
  database: gabrielwalsh_test
  username: postgres
  password: amops

production:
  <<: *default
  database: gabrielwalsh_production
  username: gabrielwalsh
  password: <%= ENV['GABRIELWALSH_DATABASE_PASSWORD'] %>